ecoledoctorale/urls.py
from django.urls import path
from ecoledoctorale.views import *

app_name = 'ecoledoctorale'

urlpatterns = [
    path('civilite/<int:ecole>/', civilite, name='civilite'),
    path('civilite/', civilite, name='civilite'), 
    path('filiation/', filiation, name='filiation'), 
    path('ecole/', ecole, name='ecole'),
    path('sport/', sport, name='sport'),
    path('autre/', autres, name='autre'),
    path('searchdom_univ/', search, name='search'),
    path('fiche/<int:code>/', fiche, name='fiche'),
    path('fiche_view/<int:code>', ViewPDF.as_view(), name="pdf_view"),
    path('fiche_download/<int:code>/', DownloadPDF.as_view(), name="pdf_download"),
    path('get_fields/', get_fields_from_school, name='get_fields'),
    path('get_supstudy/', get_supstudy, name='get_supstudy_link'),
    path('get_departments/', get_departements_from_region, name='get_departments'),
    path('step_1/', validation_step_civilite, name='civilite_step_1'),
    path('step_2/', validation_step_filiation, name='filiation_step_2'),
    #path('step_3/', validation_step_etude, name='etude_step_3'),
    path('step_4/', validation_step_ecole, name='diplome_step_4'),
    path('step_5/', validation_step_sport, name='sport_step_5'),
    path('step_6/', validation_step_autre, name='autre_step_6'),
    path('get_step_data/<int:step>/<int:code>', get_step_data, name='get_step_data'),
]

falshfsfse/urls.py
from django.urls import path
from falshfsfse.views import *

app_name = 'falshfsfse'

urlpatterns = [
    path('civilite/<int:fac>/', civilite, name='civilite'),
    path('civilite/', civilite, name='civilite'),
    path('filiation/', filiation, name='filiation'),
    path('faculte/', faculte, name='faculte'),
    path('diplome/', diplome, name='diplome'),
    path('sport/', sport, name='sport'),
    path('autre/', autres, name='autre'),
    path('searchdom_univ/', search, name='search'),
    path('fiche/<int:code>/', fiche, name='fiche'),
    path('fiche_view/<int:code>/', ViewPDF.as_view(), name='pdf_view'),
    path('fiche_download/<int:code>/', DownloadPDF.as_view(), name='pdf_download'),
    path('get_fields/', get_fields_from_school, name='get_fields'),
    path('get_supstudy/', get_supstudy, name='get_supstudy_link'),
    path('get_departments/', get_departements_from_region, name='get_departments'),
    path('step_1/', validation_step_civilite, name='civilite_step_1'),
    path('step_2/', validation_step_filiation, name='filiation_step_2'),
    path('step_3/', validation_step_etude, name='etude_step_3'),
    path('step_4/', validation_step_diplome, name='diplome_step_4'),
    path('step_5/', validation_step_sport, name='sport_step_5'),
    path('step_6/', validation_step_autre, name='autre_step_6'),
    path('get_step_data/<int:step>/<int:code>', get_step_data, name='get_step_data'),
]

logement/urls.py
from django.urls import path
from logement.views import *

app_name = 'logement'

urlpatterns = [
    path('logement_civilite/', logement_civilite, name='logement_civilite'),
    path('logement_filiation/', logement_filiation, name='logement_filiation'),
    path('logement_faculte/', logement_faculte, name='logement_faculte'),
    path('logement_sport/', logement_sport, name='logement_sport'),
    path('logement_search/', logement_search, name='logement_search'),
    
    path('logement_fiche/<int:code>/', logement_fiche, name='logement_fiche'),
    path('logement_fiche_download/<int:code>/', Logement_DownloadPDF.as_view(), name="logement_pdf_download"),
    path('logement_fiche_view/<int:code>/', Logement_ViewPDF.as_view(), name="logement_pdf_view"),

    path('step_1/', validation_step_civilite, name='civilite_step_1'),
    path('step_2/', validation_step_filiation, name='filiation_step_2'),
    path('step_3/', validation_step_etude, name='etude_step_3'),
    path('step_4/', validation_step_sport, name='sport_step_4'),
    path('get_step_data/<int:step>/<int:code>', get_step_data, name='get_step_data'),
]

preinscription/urls.py
from django.contrib import admin
from django.urls import include, path
from falshfsfse import views
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.accueil, name='accueil'),
    path('formulaire/', include('falshfsfse.urls')),
    path('logement/', include('logement.urls')),
    path('ecoledoctorale/', include('ecoledoctorale.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    url(r'^rosetta/', include('rosetta.urls'))
]

logement/models.py
from django.db import models

logement/forms.py
from django import forms
from django.utils.safestring import mark_safe  # import pour mettre une url dans le help text
from django.utils.translation import ugettext_lazy as _ #import pour la traduction d'un texte

class Logement_SearchForm(forms.Form):    
    """ forms pour l'affichage de la fiche de logement l'étudiant """
    #-----------------------------------------------------------------------------------------------------------
    code = forms.CharField(label=_("Votre code de logement"), max_length=100, required=True)

class Logement_CivilForm(forms.Form):    
    """ forms pour l'état civil """

    #Les listes des menus déroulants pour l'état civil de l'étudiant
    listesexe = [('féminin','Féminin'),('masculin','Masculin')]
    listestatutmarital = [('CELIBATAIRE', 'CELIBATAIRE'), ('MARIE(S)', 'MARIE(S)'), ('DIVORCE(E)', 'DIVORCE(E)')]
    listepremierelangue = [('français','Français'),('anglais','Anglais')]
    listestatutprofessionnel = [('SANS EMPLOI', 'SANS EMPLOI'), ('SALARIE(E)', 'SALARIE(E)'),
                                ('EN AUTO-EMPLOI', 'EN AUTO-EMPLOI')]
    listegrade = [('',''),('professeur','Professeur'),('maitreconf','Maître de Conférence'),
                                ('chargecours','Chargé de Cours'),('autre','Autres')]
    listeechelon = [('',''),('1','1'),('2','2'),('3','3'),('4','4')]
    choixhandicap = [('oui','Oui'),('non','Non')]
    dateprecisenaissance = [('oui', 'Oui'), ('non', 'Non')]
    #-----------------------------------------------------------------------------------------------------------
    nom = forms.CharField(label=_("Nom"), max_length=100, required=True)
    prenom = forms.CharField(label=_("Prénom"), max_length=100, required=False)
    datenaissance = forms.DateField(label=_("Date de naissance"), widget=forms.TextInput(attrs={'type': 'date', 'min': '1998-01-01', 'max': '2006-12-31'}),required=True)
    dateprecise = forms.ChoiceField(label=_("Est ce la date marquée sur votre acte de naissance?"),
                                    widget=forms.RadioSelect, choices=dateprecisenaissance, required=True)
    lieunaissance = forms.CharField(label=_("Lieu de naissance"), max_length=100, required=True)
    sexe = forms.CharField(label=_("Sexe"), widget=forms.Select(choices=listesexe), required=True)
    residence_parent = forms.CharField(label=_("Résidence actuelle des parents"), max_length=100, required=True)
    handicap = forms.MultipleChoiceField(label=_("Avez vous un handicap?"), widget=forms.RadioSelect, choices=choixhandicap,
                                        required=True)
    telephone = forms.CharField(label=_("Téléphone"), max_length=100, required=True,
                                help_text=_("Ne pas mettre les espaces. Exemple: 655565758"))
    email = forms.EmailField(label=_("Votre adresse e-mail"), help_text=_("exemple: accueil@univ-yaounde1.cm"), required=False)
    residence = forms.CharField(label=_("Votre résidence actuelle"), max_length=100, required=True,
                                help_text=_("Votre lieu de résidence actuelle. Exple: Obili"))
    
class Logement_FiliationForm(forms.Form):    
    """ forms pour la filiation de l'étudiant """

    #Les listes des menus déroulants pour les informations de filiation
    listenationalite = [('1', 'Cameroun'), ('2', 'Congo'), ('3', 'Gabon'),
                        ('4', 'Guinnée-équatoriale'),
                        ('6', 'République Centraficaine'), ('5', 'Nigeria'), ('8', 'Tchad'), ('7', 'Autre'), ]
    listeregion = [('2', 'ADAMAOUA'), ('1', 'CENTRE'), ('3', 'EST'), ('4', 'EXTREME-NORD'), ('5', 'LITTORAL'),
                   ('8', 'OUEST'),
                   ('6', 'NORD'), ('7', 'NORD-OUEST'), ('9', 'SUD'), ('10', 'SUD-OUEST'), ('11', 'ETRANGER')]
    listedepartement = [('', '')]
    #-----------------------------------------------------------------------------------------------------------
    nationalite = forms.CharField(label=_("Nationalité"), widget=forms.Select(choices=listenationalite), required=True)
    regionorigine = forms.CharField(label=_("Région d'origine"), widget=forms.Select(choices=listeregion), required=True)
    departementorigine = forms.CharField(label=_("Département d'origine"), widget=forms.Select(choices=listedepartement), required=True)
    nompere = forms.CharField(label=_("Nom du père"), max_length=100,help_text=_("Le nom de votre père"),required=False)
    professionpere = forms.CharField(label=_("Profession du père"), max_length=100, required=False)
    nommere = forms.CharField(label=_("Nom de la mère"), max_length=100, help_text=_("Le nom de votre mère"),required=True)
    professionmere = forms.CharField(label=_("Profession de votre mère"), max_length=100, required=True)
    telephoneparents = forms.CharField(label=_("Téléphones des parents"), max_length=100, required=False)
    nomurgence = forms.CharField(label=_("Correspondant à Yaoundé"), max_length=100, 
                                help_text=_("Remettre le nom du père ou de la mère si c'est Correspondant à Yaoundé"),
                                required=True)
    telurgence = forms.CharField(label=_("Téléphone du correspondant"), max_length=15, 
                                help_text=_("Ne pas mettre les espaces. Exemple: 655565758"),required=True)
    villeurgence = forms.CharField(label=_("Ville de résidence du contact pour urgence"), max_length=100,required=True)

class Logement_FaculteForm(forms.Form):    
    """ forms pour la faculté de l'étudiant """

    #Les listes des menus déroulants pour les informations de filiation

    listefaculte = [('1','Falculté des Arts, Lettres et Sciences Humaines'),
                    ('2','Faculté des Sciences'),
                    ('3','Faculté des Sciences de l\'Education'),
                    ('4','Faculté de Médecine et des Sciences Biomédicales'),
                    ('5','Ecole Nationale Supérieure Polytechnique de Yaoundé'),
                    ('6','Ecole Normale Supérieure'),
                    ('7','Ecole Normale Supérieure d\'Enseignement Technique d\'Ebolowa'),
                    ('8','Institut Universitaire de Technologies du Bois de Mbalmayo')
    ]
    listefilierefac = [('','')]
    listefiliere = [('','')]
    listeniveau = [('',''),('1','1'),('2','2'),('3','3'),('4','4'),
                    ('5','5'),('6','6'),('7','7'),('8','8')]
    listestatut = [('0',''),('camerounais','Etudiant camerounais'),('etranger','Etudiant étranger')]
    listeniv = [('', ''), ('TERMINALE', 'TERMINALE'), ('1ERE ANNEE LICENCE', '1ERE ANNEE LICENCE'), ('2EME ANNEE LICENCE', '2EME ANNEE LICENCE'), ('3EME ANNEE LICENCE', '3EME ANNEE LICENCE'),
                    ('MASTER 1', 'MASTER 1'),
                    ('MASTER 2', 'MASTER 2'),
                    ('DOCTORAT', 'DOCTORAT'),
                    ('SPECIALISATION', 'SPECIALISATION'),
                    ('INTERNAT', 'INTERNAT'),
    ]
    listemention = [('', ''), ('1', 'PASSABLE'), ('2', 'ASSEZ BIEN'), ('3', 'BIEN'), ('4', 'TRES BIEN'),
                    ('5', 'EXCELLENT')]
    listecite = [('',' '),('Ancienne cité','Ancienne cité'),('Nouvelle cité','Nouvelle cité'),('Cité de l\'ENS','Cié de l\'ENS'),('Minie-cité conventionnée','Minie-cité conventionnée')]
    listerenouv = [('OUI',' ')]
    listechambre = [('',''),('Individuelle','Individuelle'),('Collective','Collective')]
    #-----------------------------------------------------------------------------------------------------------
    faculte = forms.CharField(label=_("Faculté ou école"), widget=forms.Select(choices=listefaculte), required=True)
    filiere = forms.CharField(label=_("Votre filière"), widget=forms.Select(choices=listefilierefac), required=True)
    niveau  = forms.CharField(label=_("Niveau d'études"), widget=forms.Select(choices=listeniveau), required=True)
    mentionbac  = forms.CharField(label=_("Mention au Baccalauréat/GCE"), widget=forms.Select(choices=listemention), required=True)
    niveaurepris  = forms.CharField(label=_("Niveau ou classe reprise"), widget=forms.Select(choices=listeniv), required=False)
    #niveaurepris  = forms.CharField(label=_("Niveau ou classe reprise"), required=False)
    matricule = forms.CharField(label=_("Votre matricule ou code de préinscription"), max_length=100, required=True)
    nomcite  = forms.CharField(label=_("Dénomination de la Cité sollicitée"), widget=forms.Select(choices=listecite), required=False)
    renouvellement = forms.MultipleChoiceField(label=_("Est-ce un renouvellement?"), widget=forms.CheckboxSelectMultiple, choices=listerenouv,required=False)
    batiment = forms.CharField(label=_("N° Bâtiment"), max_length=100, required=False)
    chambre = forms.CharField(label=_("N° Chambre"), max_length=100, required=False)
    typechambre  = forms.CharField(label=_("Type de chambre"), widget=forms.Select(choices=listechambre), required=False)
    anneepre = forms.CharField(label=_("Votre 1ère année de résidence à la Cité-U"),required=True,
                                help_text=_("Mettez l\'année actuelle si vous n\'avez jamais eu de chambres")) 
    anneeder = forms.CharField(label=_("Votre dernière année de résidence à la Cité-U"),required=True,
                                help_text=_("Mettez l\'année actuelle si vous n\'avez jamais eu de chambres"))
 
class Logement_SportForm(forms.Form):    
    """ forms pour les activités sportives de l'étudiant """

    #Les listes des menus déroulants pour les informations de filiation
    listesport = [('athlétisme',_('Athlétisme')),('basketball',_('BasketBall')),('boxe',_('Boxe')),('football',_('Football')),
                ('gymnastique',_('Gymnastique')),('handball',_('Handball')),('judo',_('Judo')),('karate',_('Karaté')),
                ('lutte',_('Lutte')),('nambudo',_('Nambudo')),('tennistable',_('Tennis de table')),('volleyball',_('Volley-ball'))]
    listeart = [('artsplastiques',_('Arts plastiques')),('chanson',_('Chanson')),('chorale',_('Chorale')),

logement/templates/logement/logement_faculte.html
{% extends 'logement/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
    <title>{% trans "UY1 - Demande d'attribution de chambre à la Cité Universitaire" %}</title>
{% endblock title %}

{% block content %}
    {% with titre="logement_faculté"%}
        {% include 'logement/logement_menuetape.html' %}
    {% endwith %}
<div class="col-md-6">
    <h3>{% trans "Demande de logement à la cité Universitaire" %}</h3>
    <form id='faculte_form' name='faculte_form' action="" method="post" class='f1'>
        {% csrf_token %}
        
        {{ logement_faculte_form| crispy }}
        
        <input type="button" onclick="prev()" name ="bouton_faculte_prev" value="Précédent" class="btn btn-charte btn-lg" style="width: 116px">
        <input type="submit" value="Suivant" class="btn btn-charte btn-lg" style="width: 116px">   
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> 
<script type="text/javascript">

    function prev() {
        window.location.href = "/logement/logement_filiation/"
    }

    $( document ).ready(function() {
        function loadfield(callback){
            if ($('#id_faculte').val() != "") {
                getFiliere()
            }
        }

        $('#id_faculte').change(function () {
            if ($('#id_faculte').val() != "") {
                getFiliere()
            }
        });

        function getFiliere(){
            $.ajax({
                url: "{% url 'falshfsfse:get_fields' %}",
                type: "POST",
                data: {
                    'school_id': $('#id_faculte').val(),
                    'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val()
                },
                dataType: 'json',
                success: function (data, status) {
                    //alert(res);
                    // salert(status);
                    // var selectValues = { // Utiliser les bonnes donnees des que dispo
                    //   "1": "test 1",
                    //   "2": "test 2"
                    // };
                    var $mySelect1 = $('#id_filiere');
                    document.getElementById("id_filiere").options.length = 0;
                    $.each(data['data'], function(key, value) {
                    var $option = $("<option/>", {
                        value: value.id,
                        text: value.name
                    });
                    $mySelect1.append($option);
                    });
                },
                error: function (data) {
                    // alert(data.status);                                                                                                                          
                }
            });
        }

        //here
        function reprise(){
            if(sessionStorage.getItem("LogCodeUnique") != null && sessionStorage.getItem("LogCodeUnique") != "" && sessionStorage.getItem("LogCodeUnique") != undefined){
                $.ajax({
                    //type: 'POST',
                    url: '/logement/get_step_data/3/'+sessionStorage.getItem("LogCodeUnique"),
                    data: {
                        //csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
                    },
                    dataType: 'json',
                    beforeSend: function() {
                        //$('#ftco-loader').addClass('show');
                    },
                    success: function (data) {
                        //alert('ok')
                        // document.faculte_form.faculte.value = data['faculte'] == undefined ? "" : data['faculte']
                        if (data['faculte'] != undefined) {
                            $('#id_faculte').val(data['faculte']).trigger('change');
                        }
                        
                        // setTimeout(function(){},1000);
                        document.faculte_form.filiere.value = data['filiere'] == undefined ? "" : data['filiere']
                        document.faculte_form.niveau.value = data['niveau'] == undefined ? "" : data['niveau']
                        document.faculte_form.mentionbac.value = data['mentionbac'] == undefined ? "" : data['mentionbac']
                        document.faculte_form.niveaurepris.value = data['niveaurepris'] == undefined ? "" : data['niveaurepris']
                        document.faculte_form.matricule.value = data['matricule'] == undefined ? "" : data['matricule']
                        document.faculte_form.nomcite.value = data['nomcite'] == undefined ? "" : data['nomcite']
                        document.faculte_form.renouvellement.value = data['renouvellement'] == undefined ? "" : data['renouvellement']
                        document.faculte_form.batiment.value = data['batiment'] == undefined ? "" : data['batiment']
                        document.faculte_form.chambre.value = data['chambre'] == undefined ? "" : data['chambre']
                        document.faculte_form.typechambre.value = data['typechambre'] == undefined ? "" : data['typechambre']
                        document.faculte_form.anneepre.value = data['anneepre'] == undefined ? "" : data['anneepre']
                        document.faculte_form.anneeder.value = data['anneeder'] == undefined ? "" : data['anneeder']
                        // $('#id_premierchoix').val(data['premierchoix']).trigger('change');
                    },
                    error: function (data) {
                        //$('#ftco-loader').removeClass('show');
                        //alert("Erreur AJAX");                                                                                                                          
                    }
                })
            }
        }

        $.when( loadfield() ).done(function() {
            setTimeout(function(){

                reprise();
            },100); // 1/10 secondes
            
        });



        $( document ).on('submit', '#faculte_form', function(e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '/logement/step_3/',
                data: {
                    faculte: $('#id_faculte').val(),
                    filiere: $('#id_filiere').val(),
                    niveau: $('#id_niveau').val(),
                    mentionbac: $('#id_mentionbac').val(),
                    niveaurepris: $('#id_niveaurepris').val(),
                    matricule: $('#id_matricule').val(),
                    nomcite: $('#id_nomcite').val(),
                    renouvellement: $('#id_renouvellement_1').val(),
                    batiment: $('#id_batiment').val(),
                    chambre: $('#id_chambre').val(),
                    typechambre: $('#id_typechambre').val(),
                    anneepre: $('#id_anneepre').val(),
                    anneeder: $('#id_anneeder').val(),
                    

                    csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
                },
                beforeSend: function() {
                    $('#ftco-loader').addClass('show');
                },
                success: function (data) {
                    //$('#ftco-loader').removeClass('show');
                    //alert("ok") 
                    window.location.href = "/logement/logement_sport/" // Le rediriger vers le step 4
                    //Penser a sauver les donnees dans la session                                                                                                            
                },
                error: function (data) {
                    $('#ftco-loader').removeClass('show');
                    alert("Erreur au niveau du serveur");                                                                                                                          
                }
            })

        });

    });

</script>
{% endblock content %}

{% block aide %}
    {% include 'logement/logement_menuaide.html' %}
{% endblock %}

logement/templates/logement/logement_filiation.html
{% extends 'logement/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
    <title>{% trans "UY1 - Demande d'attribution de chambre à la Cité Universitaire" %}</title>
{% endblock title %}

{% block content %}
    {% with titre="logement_filiation"%}
        {% include 'logement/logement_menuetape.html' %}
    {% endwith %}
<div class="col-md-6">
    <h3>{% trans "Demande de logement à la cité Universitaire" %}</h3>
    <form id='filiation_form' action="" name='filiation_form' method="post" class='f1'>
        {% csrf_token %}
        
        {{ logement_filiation_form| crispy }}
        
        <input type="button" onclick="prev()" name ="bouton_filiation_prev" value="Précédent" class="btn btn-charte btn-lg" style="width: 116px">
        <input type="submit" value="Suivant" class="btn btn-charte btn-lg" style="width: 116px">   
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> 
<script type="text/javascript">

    function prev() {
        window.location.href = "/logement/logement_civilite/"
    }  

    $( document ).ready(function() {
        $.when( loadd() ).done(function() {
            setTimeout(function(){

                reprise();
            },50);
            
        });

        function reprise(){
            if(sessionStorage.getItem("LogCodeUnique") != null && sessionStorage.getItem("LogCodeUnique") != "" && sessionStorage.getItem("LogCodeUnique") != undefined){
                // Recharger les valeurs soumises dans les champs
                $.ajax({
                    //type: 'POST',
                    url: '/logement/get_step_data/2/'+sessionStorage.getItem("LogCodeUnique"),
                    data: {
                        //csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
                    },
                    dataType: 'json',
                    beforeSend: function() {
                        //$('#ftco-loader').addClass('show');
                    },
                    success: function (data) {
                        //alert('ok')
                        document.filiation_form.nationalite.value = data['nationalite'] == undefined ? "" : data['nationalite']
                        //document.filiation_form.regionorigine.value = data['regionorigine'] == undefined ? "" : data['regionorigine']
                        $('#id_regionorigine').val(data['regionorigine']).trigger('change');
                        setTimeout(function(){
                            document.filiation_form.departementorigine.value = data['departementorigine'] == undefined ? "" : data['departementorigine']
                        },5000);
                        document.filiation_form.departementorigine.value = data['departementorigine'] == undefined ? "" : data['departementorigine']
                        document.filiation_form.nompere.value = data['nompere'] == undefined ? "" : data['nompere']
                        document.filiation_form.professionpere.value = data['professionpere'] == undefined ? "" : data['professionpere']
                        document.filiation_form.nommere.value = data['nommere'] == undefined ? "" : data['nommere']
                        document.filiation_form.professionmere.value = data['professionmere'] == undefined ? "" : data['professionmere']
                        document.filiation_form.nomurgence.value = data['nomurgence'] == undefined ? "" : data['nomurgence']
                        document.filiation_form.telurgence.value = data['telurgence'] == undefined ? "" : data['telurgence']
                        document.filiation_form.villeurgence.value = data['villeurgence'] == undefined ? "" : data['villeurgence']
                    },
                    error: function (data) {
                        //$('#ftco-loader').removeClass('show');
                        //alert("Erreur AJAX");                                                                                                                          
                    }
                })
            }
        }

        function loadd(callback) {
            loadDepart()
        }
    
        $("#id_regionorigine").change(function () {
            loadDepart()

        });

        $("#id_nationalite").change(function () {
            if ($(this).val() != "1") {
                document.getElementById("id_regionorigine").options.length = 0;
                var $option = $("<option/>", {
                    value: 11,
                    text: "ETRANGER"
                });
                $('#id_regionorigine').append($option);

                document.getElementById("id_departementorigine").options.length = 0;
                var $option = $("<option/>", {
                    value: 59,
                    text: "ETRANGER"
                });
                $('#id_departementorigine').append($option);
            }
            else{
                var selectValues = { 
                    "2": "ADAMAOUA",
                    "1": "CENTRE",
                    "3": "EST",
                    "4": "EXTREME-NORD",
                    "5": "LITTORAL",
                    "8": "OUEST",
                    "6": "NORD",
                    "7": "NORD-OUEST",
                    "9": "SUD",
                    "10": "SUD-OUEST"
                };
                document.getElementById("id_regionorigine").options.length = 0;
                $.each(selectValues, function(key, value) {
                    var $option = $("<option/>", {
                        value: key,
                        text: value
                    });
                    $('#id_regionorigine').append($option);
                    loadDepart()
                });
            }

        });

        function loadDepart() {
            var regionID = $("#id_regionorigine").val();
            $.ajax({ 
                url: "{% url 'falshfsfse:get_departments' %}",
                type: "POST",
                data: {
                  'region_id': regionID,
                  'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val()
                },
                dataType: 'json',
                success: function (data, status) {
                  // var selectValues = { // Utiliser les bonnes donnees des que dispo
                  //     "1": "test 1",
                  //     "2": "test 2"
                  //   };
                    var $departement = $('#id_departementorigine');
                    // var select = $("<select>");
                    document.getElementById("id_departementorigine").options.length = 0;
                    $.each(data['data'], function(key, value) {
                       // select.append( $('<option></option>').val(value.id).html(value.name) );
                        var $option = $("<option>", {
                            value: value.id,
                            text: value.name
                        });
                        $departement.append($option);
                    });
                    // $departement.append(select.html());
                },
                error: function (data) {
                    // alert("Erreur au niveau du serveur");                                                                                                                           
                }
            });
        }

    });

    $( document ).on('submit', '#filiation_form', function(e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '/logement/step_2/',
            data: {
                nationalite: $('#id_nationalite').val(),
                regionorigine: $('#id_regionorigine').val(),
                departementorigine: $('#id_departementorigine').val(),
                nompere: $('#id_nompere').val(),
                professionpere: $('#id_professionpere').val(),
                nommere: $('#id_nommere').val(),
                professionmere: $('#id_professionmere').val(),
                telephoneparents: $('#id_telephoneparents').val(),
                nomurgence: $('#id_nomurgence').val(),
                telurgence: $('#id_telurgence').val(),
                villeurgence: $('#id_villeurgence').val(),
                

                csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
            },
            beforeSend: function() {
                $('#ftco-loader').addClass('show');
            },
            success: function (data) {
                //$('#ftco-loader').removeClass('show');
                //alert("ok") 
                window.location.href = "/logement/logement_faculte/" // Le rediriger vers le step 3
                //Penser a sauver les donnees dans la session                                                                                                            
            },
            error: function (data) {
                $('#ftco-loader').removeClass('show');
                alert("Erreur au niveau du serveur");                                                                                                                          
            }
        })

    });

</script>
{% endblock content %}

{% block aide %}
    {% include 'logement/logement_menuaide.html' %}
{% endblock %}