ecoledoctorale/urls.py
from django.urls import path
from ecoledoctorale.views import *

app_name = 'ecoledoctorale'

urlpatterns = [
    path('civilite/<int:ecole>/', civilite, name='civilite'),
    path('civilite/', civilite, name='civilite'), 
    path('filiation/', filiation, name='filiation'), 
    path('ecole/', ecole, name='ecole'),
    path('sport/', sport, name='sport'),
    path('autre/', autres, name='autre'),
    path('searchdom_univ/', search, name='search'),
    path('fiche/<int:code>/', fiche, name='fiche'),
    path('fiche_view/<int:code>', ViewPDF.as_view(), name="pdf_view"),
    path('fiche_download/<int:code>/', DownloadPDF.as_view(), name="pdf_download"),
    path('get_fields/', get_fields_from_school, name='get_fields'),
    path('get_supstudy/', get_supstudy, name='get_supstudy_link'),
    path('get_departments/', get_departements_from_region, name='get_departments'),
    path('step_1/', validation_step_civilite, name='civilite_step_1'),
    path('step_2/', validation_step_filiation, name='filiation_step_2'),
    #path('step_3/', validation_step_etude, name='etude_step_3'),
    path('step_4/', validation_step_ecole, name='diplome_step_4'),
    path('step_5/', validation_step_sport, name='sport_step_5'),
    path('step_6/', validation_step_autre, name='autre_step_6'),
    path('get_step_data/<int:step>/<int:code>', get_step_data, name='get_step_data'),
]

falshfsfse/urls.py
from django.urls import path
from falshfsfse.views import *

app_name = 'falshfsfse'

urlpatterns = [
    path('civilite/<int:fac>/', civilite, name='civilite'),
    path('civilite/', civilite, name='civilite'),
    path('filiation/', filiation, name='filiation'),
    path('faculte/', faculte, name='faculte'),
    path('diplome/', diplome, name='diplome'),
    path('sport/', sport, name='sport'),
    path('autre/', autres, name='autre'),
    path('searchdom_univ/', search, name='search'),
    path('fiche/<int:code>/', fiche, name='fiche'),
    path('fiche_view/<int:code>/', ViewPDF.as_view(), name='pdf_view'),
    path('fiche_download/<int:code>/', DownloadPDF.as_view(), name='pdf_download'),
    path('get_fields/', get_fields_from_school, name='get_fields'),
    path('get_supstudy/', get_supstudy, name='get_supstudy_link'),
    path('get_departments/', get_departements_from_region, name='get_departments'),
    path('step_1/', validation_step_civilite, name='civilite_step_1'),
    path('step_2/', validation_step_filiation, name='filiation_step_2'),
    path('step_3/', validation_step_etude, name='etude_step_3'),
    path('step_4/', validation_step_diplome, name='diplome_step_4'),
    path('step_5/', validation_step_sport, name='sport_step_5'),
    path('step_6/', validation_step_autre, name='autre_step_6'),
    path('get_step_data/<int:step>/<int:code>', get_step_data, name='get_step_data'),
]

logement/urls.py
from django.urls import path
from logement.views import *

app_name = 'logement'

urlpatterns = [
    path('logement_civilite/', logement_civilite, name='logement_civilite'),
    path('logement_filiation/', logement_filiation, name='logement_filiation'),
    path('logement_faculte/', logement_faculte, name='logement_faculte'),
    path('logement_sport/', logement_sport, name='logement_sport'),
    path('logement_search/', logement_search, name='logement_search'),
    
    path('logement_fiche/<int:code>/', logement_fiche, name='logement_fiche'),
    path('logement_fiche_download/<int:code>/', Logement_DownloadPDF.as_view(), name="logement_pdf_download"),
    path('logement_fiche_view/<int:code>/', Logement_ViewPDF.as_view(), name="logement_pdf_view"),

    path('step_1/', validation_step_civilite, name='civilite_step_1'),
    path('step_2/', validation_step_filiation, name='filiation_step_2'),
    path('step_3/', validation_step_etude, name='etude_step_3'),
    path('step_4/', validation_step_sport, name='sport_step_4'),
    path('get_step_data/<int:step>/<int:code>', get_step_data, name='get_step_data'),
]

preinscription/urls.py
from django.contrib import admin
from django.urls import include, path
from falshfsfse import views
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.accueil, name='accueil'),
    path('formulaire/', include('falshfsfse.urls')),
    path('logement/', include('logement.urls')),
    path('ecoledoctorale/', include('ecoledoctorale.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    url(r'^rosetta/', include('rosetta.urls'))
]

ecoledoctorale/models.py
from django.db import models

# Create your models here.

ecoledoctorale/forms.py
import datetime
from django import forms
from django.utils.safestring import mark_safe  # import pour mettre une url dans le help text
from django.utils.translation import ugettext_lazy as _  # import pour la traduction d'un texte


class EcoleForm(forms.Form):    
    """ forms pour la faculté de l'étudiant """

    #Les listes des menus déroulants pour les informations de filiation
    liste_ecole_doc = [('9',_('CRFD Arts, Langues et Cultures')),('12',_('CRFD Sciences Humaines, Sociales et Educatives')),
                    ('11',_('CRFD Sciences et Technologies')),('10',_('CRFD Sciences de la Vie, Santé et Environnement'))]
    liste_unite_recherche = [('','')]
    liste_cycle = [('MASTER II','MASTER II'), ('DOCTORAT','DOCTORAT')]
    listedisponibilite = [('Temps plein',_('Temps plein')),('Temps partiel',_('Temps partiel'))]
    listeformationinitiale = [('LMD',_('LMD')),('Sciences de l\'ingénieur',_('Sciences de l\'ingénieur')),('Etudes médicales',_('Etudes médicales')),
                            ('Etudes pharmaceutiques',_('Etudes pharmaceutiques')),('Etudes odonto-stomatologiques',_('Etudes odonto-stomatologiques'))]
    listenaturemasterun = [('recherche',_('Master 1 recherche')),('professionel',_('Master 1 professionel'))]
    listefinancement = [('personnelle',_('Personnelle')),('bourse',_('Bourse')),('salarié',_('Salarié'))]
    #-----------------------------------------------------------------------------------------------------------
    matricule_ext = forms.CharField(label=_("Matricule"), required=False,
                                help_text=_("Mettre votre matricule lors de votre licence si vous en avez un."))
    ecoledoc = forms.CharField(label=_("Votre école doctorale"), required=True, widget=forms.TextInput(attrs={'disabled': 'disabled'}))
    uniterecherche = forms.CharField(label=_("Votre unité de recherche"), widget=forms.Select(choices=liste_unite_recherche), required=True)
    cycle = forms.CharField(label=_("Cycle d'inscription"), widget=forms.Select(choices=liste_cycle), required=True)
    disponibilite  = forms.CharField(label=_("Disponibilité"), widget=forms.Select(choices=listedisponibilite), required=True)
    formationinitiale  = forms.CharField(label=_("Formation initiale"), widget=forms.Select(choices=listeformationinitiale), required=False)
    naturelicence  = forms.CharField(label=_("Filière de la licence"), 
                    help_text=_("Mettre la filière de votre diplôme de licence."),required=False)
    optionlicence  = forms.CharField(label=_("Option de la licence"),
                    help_text=_("Votre spécialité en licence."),required=False)
    anneelicence  = forms.IntegerField(label=_("Nombres d\'année en licence"), required=True,
                                    min_value=0, max_value=10,
                                    help_text=_("Mettre le nombre d\'années effectuées en Faculté pour avoir votre licence"))
    naturemasterun = forms.CharField(label=_("Nature de votre Master 1"),widget=forms.Select(choices=listenaturemasterun),required=True)
    specialitemasterun = forms.CharField(label=_("Spécialité de votre Master 1"),required=False)
    etablissementmasterun = forms.CharField(label=_("Etablissement de votre Master 1"),required=False,
                                        help_text=_("Mettre l\'établissement dans lequel votre master 1 a été validé."))
    departementmasterun = forms.CharField(label=_("Département de votre Master 1"),required=False,
                                        help_text=_("Mettre le département dans lequel votre master 1 a été validé."))
    anneemasterun  = forms.IntegerField(label=_("Nombres d\'année en Master 1"), required=True,
                                    min_value=0, max_value=10,
                                    help_text=_("Mettre le nombre d\'années effectuées en Faculté pour avoir votre master 1"))
    encadreur1  = forms.CharField(label=_("Non de l'encadreur 1"),help_text=_("Nom de votree ncadreur."),required=True)
    encadreur2  = forms.CharField(label=_("Non de l'encadreur 2"),help_text=_("Laissez vide si vous avez un seul encadeur."),required=False)
    sourcefinancement = forms.CharField(label=_("Sources de financements"),
                                        widget=forms.Select(choices=listefinancement), required=True)
    motivationthese = forms.CharField(label=_("Motivation à engager la recherche"),required=True,widget=forms.Textarea(),
                                        help_text=_("Expliquer votre motivation pour engager, au minimum, 3 ans de recherche pour obtenir votre doctorat"))
    resumethese = forms.CharField(label=_("Résumé de votre projet de thèse (uniquement si vous voulez faire un doctorat)"),
                                required=False,widget=forms.Textarea(),
                                help_text=mark_safe("Cliquez <a href='https://lrl.uca.fr/article338.html' target='_blank'>ici pour voir un exemple.</a>"))

class SearchForm(forms.Form):
    """ forms pour l'affichage de la fiche de l'étudiant """
    # -----------------------------------------------------------------------------------------------------------
    code = forms.CharField(label=_("Votre code de préinscription"), max_length=100, required=True)


class CivilForm(forms.Form):
    """ forms pour l'état civil """

    # Les listes des menus déroulants pour l'état civil de l'étudiant
    listesexe = [('féminin', _('Féminin')), ('masculin', _('Masculin'))]
    listestatutmarital = [('Celibataire', _('CELIBATAIRE')), ('marie', _('MARIE(S)')), ('divorce', _('DIVORCE(E)'))]
    listepremierelangue = [('français', _('Français')), ('anglais', _('Anglais'))]
    listestatutprofessionnel = [('SANS EMPLOI', _('SANS EMPLOI')), ('SALARIE(E)', _('SALARIE(E)')),
                                ('EN AUTO-EMPLOI', _('EN AUTO-EMPLOI'))]
    listegrade = [('0', ' '), ('professeur', _('Professeur')), ('maitreconf', _('Maître de Conférence')),
                  ('chargecours', _('Chargé de Cours')), ('autre', _('Autres'))]
    listeechelon = [('0', ' '), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')]
    dateprecisenaissance = [('oui', _('Oui')), ('non', _('Non'))]
    # on suppose qu'il faut au moins avoir 15 ans pour s'inscrire à l'université de Uy1
    diffdate = datetime.date.today() - datetime.timedelta(days=4380)  # 15 ans corresponds à environ 5475 jours

    # ------------------------------------------------------------------------------------------------------------
    matricule = forms.CharField(label=_("Matricule de UY1"), required=False,
                                help_text=_("Mettre votre matricule de UY1 si vous en avez un."))
    nom = forms.CharField(label=_("Nom(s)"), max_length=100, required=True)
    prenom = forms.CharField(label=_("Prénom(s)"), max_length=100, required=False)
    datenaissance = forms.DateField(label=_("Date de naissance"), widget=forms.TextInput(
        attrs={'type': 'date', 'min': '1900-01-01', 'max': diffdate}),
                                    required=True)
    dateprecise = forms.ChoiceField(label=_("Est ce la date marquée sur votre acte de naissance?"),
                                    widget=forms.RadioSelect, choices=dateprecisenaissance, required=True)
    lieunaissance = forms.CharField(label=_("Lieu de naissance"), max_length=100, required=True)
    numerocni = forms.CharField(label=_("Numéro de CNI"), max_length=100, required=False)
    sexe = forms.CharField(label=_("Sexe"), widget=forms.Select(choices=listesexe), required=True)
    adresse = forms.CharField(label=_("Adresse"), max_length=100,
                              help_text=_("Votre quartier de résidence. Exemple: Obili"),
                              required=True)
    telephone = forms.CharField(label=_("Téléphone"), max_length=100, required=True,
                                help_text=_("Ne pas mettre les espaces. Exemple: 655565758"))
    email = forms.EmailField(label=_("Votre adresse e-mail"), help_text=_("exemple: accueil@univ-yaounde1.cm"),
                             required=False)
    statutmarital = forms.CharField(label=_("Statut marital"), widget=forms.Select(choices=listestatutmarital),
                                    required=True)
    premierelangue = forms.CharField(label=_("Première langue"), widget=forms.Select(choices=listepremierelangue),
                                     required=True)
    statutprofessionnel = forms.CharField(label=_("Statut professionnel"),
                                          widget=forms.Select(choices=listestatutprofessionnel),
                                          required=False)
    profession = forms.CharField(help_text=_("Votre profession si vous en avez une."),
                                 label=_("Profession"), max_length=100, required=False)
    lieudujob = forms.CharField(label=_("Lieu de votre emploi"), max_length=100, required=False,
                                help_text=_("Si vous avez un emploi."))
    grade = forms.CharField(label=_("Grade"), widget=forms.Select(choices=listegrade), required=False,
                            help_text=_("Uniquement si vous avez un emploi."))
    echelon = forms.CharField(label=_("Echelon"), widget=forms.Select(choices=listeechelon), required=False,
                              help_text=_("Uniquement si vous avez un emploi."))


class FiliationForm(forms.Form):
    """ forms pour la filiation de l'étudiant """

    # Les listes des menus déroulants pour les informations de filiation
    listenationalite = [('1', _('Cameroun')), ('2', _('Congo')), ('3', _('Gabon')),
                        ('4', _('Guinnée-équatoriale')), ('5', _('Nigeria')),
                        ('6', _('République Centraficaine')), ('8', _('Tchad')),('7', _('Autre'))]
    listeregion = [('2', _('ADAMAOUA')), ('1', _('CENTRE')), ('3', _('EST')), ('4', _('EXTREME-NORD')), ('5', _('LITTORAL')),
                   ('8', _('OUEST')),('6', _('NORD')), ('7', _('NORD-OUEST')), ('9', _('SUD')), 

ecoledoctorale/templates/ecoledoctorale/boutonsuivant.html
<div class="row m-auto center">
    <div class="col-sm-12 m-auto">
        {%if text == "Modifier"  %}
            <button type="submit" class="btn  btn-around2" style="min-width: 150px; max-width: 100%;">
                <i class="fas fa-edit"></i> Modifier
            </button>
        {% else %}
            <button type="submit" class="btn  btn-around2" style="min-width: 150px; max-width: 100%;">
                <i class="fas fa-plus"></i> Suivant
            </button>
        {% endif %}
    </div>
</div>

ecoledoctorale/templates/ecoledoctorale/civilite.html
{% extends 'ecoledoctorale/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
    {% with titre="civilité"%}
        {% include 'ecoledoctorale/menuetape.html' %}
    {% endwith %}
<div class="col-md-6">
    <h3>{% trans 'Préinscription en' %} {{ request.session.ecole }}</h3>
    <h6>{% trans 'Tous les champs marqués d\'un' %} <span style="color:red; margin-top:3px;">*</span> {% trans 'sont obligatoires.' %}</h6>
    <form id='civilite_form' name='civilite_form' class='f1' name='civilite_form'>
        {% csrf_token %}
        
        {{ civilite_form| crispy }}
        
        <!-- <input type="button" onclick="prev()" name = "bouton_autre_prev" value="Précédent" class="btn btn-charte btn-lg" style="width: 116px"> -->
        <input type="submit" value="Suivant" class="btn btn-charte btn-lg" style="width: 116px">   
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> 
<script type="text/javascript">


    // function prev() {
    //     location.replace("/formulaire/autre/{{ request.session.code_fac }}")
    // }
    $( document ).ready(function() {


        function masquerShow(){
            // Masquer certains champs si statut professionel == Sans emploi
            if ($('#id_statutprofessionnel').val() == "SANS EMPLOI" || $('#id_statutprofessionnel').val() == "EN AUTO-EMPLOI" || $('#id_statutprofessionnel').val() == null) {
                $('#div_id_profession').hide()
                $('#div_id_lieudujob').hide()
                $('#div_id_grade').hide()
                $('#div_id_echelon').hide()
            }

            $("#id_statutprofessionnel").change(function () {

                if ($(this).val() == "SALARIE(E)") {
                    $('#div_id_profession').show()
                    $('#div_id_lieudujob').show()
                    $('#div_id_grade').show()
                    $('#div_id_echelon').show()
                }
                else{
                    $('#div_id_profession').hide()
                    $('#div_id_lieudujob').hide()
                    $('#div_id_grade').hide()
                    $('#div_id_echelon').hide()
                }

            });
        }


        function loadfield(callback){

            // Recharger les valeurs soumises dans les champs
            $.ajax({
                //type: 'POST',
                url: '/ecoledoctorale/get_step_data/1/'+sessionStorage.getItem("codeUnique"),
                data: {
                    //csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
                },
                dataType: 'json',
                beforeSend: function() {
                    //$('#ftco-loader').addClass('show');
                },
                success: function (data) {
                    if (data['matricule'] != undefined && data['matricule'] != ""){
                            document.civilite_form.matricule.value = data['matricule']  
                        }
                    document.civilite_form.prenom.value = data['prenom'] == undefined ? "" : data['prenom']
                    document.civilite_form.nom.value = data['nom'] == undefined ? "" : data['nom']
                    document.civilite_form.sexe.value = data['sexe'] == undefined ? "" : data['sexe']
                    document.civilite_form.datenaissance.value = data['datenaissance'] == undefined ? "" : data['datenaissance']
                    document.civilite_form.dateprecise.value = data['dateprecise'] == undefined ? "" : data['dateprecise']
                    document.civilite_form.lieunaissance.value = data['lieunaissance'] == undefined ? "" : data['lieunaissance']
                    document.civilite_form.numerocni.value = data['numerocni'] == undefined ? "" : data['numerocni']
                    document.civilite_form.sexe.value = data['sexe'] == undefined ? "" : data['sexe']
                    document.civilite_form.adresse.value = data['adresse'] == undefined ? "" : data['adresse']
                    document.civilite_form.telephone.value = data['telephone'] == undefined ? "" : data['telephone']
                    document.civilite_form.email.value = data['email'] == undefined ? "" : data['email']
                    document.civilite_form.statutmarital.value = data['statutmarital'] == undefined ? "" : data['statutmarital']
                    document.civilite_form.premierelangue.value = data['premierelangue'] == undefined ? "" : data['premierelangue']
                    document.civilite_form.statutprofessionnel.value = data['statutprofessionnel'] == undefined ? "" : data['statutprofessionnel']
                    if (data['statutprofessionnel'] == "SALARIE(E)") {
                        $('#div_id_profession').show()
                        $('#div_id_lieudujob').show()
                        $('#div_id_grade').show()
                        $('#div_id_echelon').show()
                    }
                    document.civilite_form.profession.value = data['profession'] == undefined ? "" : data['profession']
                    document.civilite_form.lieudujob.value = data['lieudujob'] == undefined ? "" : data['lieudujob']
                    document.civilite_form.grade.value = data['grade'] == undefined ? "" : data['grade']
                    document.civilite_form.echelon.value = data['echelon'] == undefined ? "" : data['echelon']

                },
                error: function (data) {
                    //$('#ftco-loader').removeClass('show');
                    //alert("Erreur AJAX");                                                                                                                          
                }
            })
        }

        $.when( loadfield() ).done(function() {
            setTimeout(function(){

                masquerShow();
            },100);
            
        });
    });


    $( document ).on('submit', '#civilite_form', function(e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '/ecoledoctorale/step_1/',
            data: {
                matricule: $('#id_matricule').val(), 
                prenom: $('#id_prenom').val(),
                nom: $('#id_nom').val(),
                datenaissance: $('#id_datenaissance').val(),
                dateprecise: document.civilite_form.dateprecise.value,
                lieunaissance: $('#id_lieunaissance').val(),
                numerocni: $('#id_numerocni').val(),
                sexe: $('#id_sexe').val(),
                adresse: $('#id_adresse').val(),
                telephone: $('#id_telephone').val(),
                email: $('#id_email').val(),
                statutmarital: $('#id_statutmarital').val(),
                premierelangue: $('#id_premierelangue').val(),
                statutprofessionnel: $('#id_statutprofessionnel').val(),
                profession: $('#id_profession').val(),
                lieudujob: $('#id_lieudujob').val(),
                grade: $('#id_grade').val(),
                echelon: $('#id_echelon').val(),

                csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
            },
            beforeSend: function() {
                $('#ftco-loader').addClass('show');
            },
            success: function (data) {
                //$('#ftco-loader').removeClass('show');
                sessionStorage.codeUnique = data['code']
                window.location.href = "/ecoledoctorale/autre/" // Le rediriger vers le step 2
                // Penser a sauver les donnees dans la session
                // Penser à vérifier que tous les champs sont remplis avant d'envoyer les données
            },
            error: function (data) {
                $('#ftco-loader').removeClass('show');
                //alert("Erreur AJAX");                                                                                                                          
            }
        })

    });

</script>
{% endblock content %}

ecoledoctorale/templates/ecoledoctorale/ecole.html
{% extends 'ecoledoctorale/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
    {% with titre="école"%}
        {% include 'ecoledoctorale/menuetape.html' %}
    {% endwith %}
<div class="col-md-6">
    <h3>{% trans 'Préinscription en' %} <span id="ec">{{ request.session.ecole }}</span></h3>
    <form id='ecole_form' name='ecole_form' action="" method="post" class='f1'>
        {% csrf_token %}
        
        {{ ecole_form| crispy }}

        <input type="button" onclick="prev()" name ="bouton_ecole_prev" value="Précédent" class="btn btn-charte btn-lg" style="width: 116px">
        <input type="submit" name = "bouton_ecole" value="Suivant" class="btn btn-charte btn-lg" style="width: 116px">   
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> 
<script type="text/javascript">

    function prev() {
        window.location.href = "/ecoledoctorale/ecole/"
    }

    $( document ).ready(function() {
        
        // Recharger les valeurs soumises dans les champs
        
        $.when( loadfield() ).done(function() {
            setTimeout(function(){

                reprise();
            },100); // 1/10 secondes
                
        });
        document.getElementById('id_ecoledoc').value = $('#ec').text(),

        school = '{{ request.session.ecole }}';
        
        function reprise(){ // Recharger les valeurs soumises dans les champs
        
            $.ajax({
                //type: 'POST',
                url: '/ecoledoctorale/get_step_data/4/'+sessionStorage.getItem("codeUnique"),
                data: {
                    //csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
                },
                dataType: 'json',
                beforeSend: function() {
                    //$('#ftco-loader').addClass('show');
                },
                success: function (data) {
                    //alert('ok')
                    document.ecole_form.matricule_ext.value = data['matricule_ext'] == undefined ? "" : data['matricule_ext']
                    // document.ecole_form.ecoledoc.value = data['ecoledoc'] == undefined ? "" : data['ecoledoc']
                    document.ecole_form.uniterecherche.value = data['uniterecherche'] == undefined ? "" : data['uniterecherche']
                    document.ecole_form.disponibilite.value = data['disponibilite'] == undefined ? "" : data['disponibilite']
                    document.ecole_form.formationinitiale.value = data['formationinitiale'] == undefined ? "" : data['formationinitiale']
                    document.ecole_form.naturelicence.value = data['naturelicence'] == undefined ? "" : data['naturelicence']
                    document.ecole_form.optionlicence.value = data['optionlicence'] == undefined ? "" : data['optionlicence']
                    document.ecole_form.anneelicence.value = data['anneelicence'] == undefined ? "" : data['anneelicence']
                    document.ecole_form.naturemasterun.value = data['naturemasterun'] == undefined ? "" : data['naturemasterun']
                    document.ecole_form.specialitemasterun.value = data['specialitemasterun'] == undefined ? "" : data['specialitemasterun']
                    document.ecole_form.etablissementmasterun.value = data['etablissementmasterun'] == undefined ? "" : data['etablissementmasterun']
                    document.ecole_form.departementmasterun.value = data['departementmasterun'] == undefined ? "" : data['departementmasterun']
                    document.ecole_form.anneemasterun.value = data['anneemasterun'] == undefined ? "" : data['anneemasterun']
                    document.ecole_form.sourcefinancement.value = data['sourcefinancement'] == undefined ? "" : data['sourcefinancement']
                    document.ecole_form.motivationthese.value = data['motivationthese'] == undefined ? "" : data['motivationthese']
                    document.ecole_form.resumethese.value = data['resumethese'] == undefined ? "" : data['resumethese']
                },
                error: function (data) {
                    //$('#ftco-loader').removeClass('show');
                    //alert("Erreur AJAX");                                                                                                                          
                }
            })
        }
    });

    function loadfield(callback){
            $.ajax({
                url: "{% url 'falshfsfse:get_fields' %}",
                type: "POST",
                data: {
                    'school_id': '{{ request.session.code_ecole }}',
                    'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val()
                },
                dataType: 'json',
                success: function (data, status) {
                    
                    var $mySelect1 = $('#id_uniterecherche');
                    //
                    $.each(data['data'], function(key, value) {
                      var $option = $("<option/>", {
                        value: value.name,
                        text: value.name
                      });
                      $mySelect1.append($option);
                    });
                },
                error: function (data) {
                    //alert(data.status);                                                                                                                          
                }
            });
            return true;
    }

    

        


    $( document ).on('submit', '#ecole_form', function(e) {
            e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '/ecoledoctorale/step_4/',
            data: {
                matricule_ext: $('#id_matricule_ext').val(),
                ecoledoc: '{{ request.session.ecole }}',
                // codeecole: '{{ request.session.code_ecole }}',
                uniterecherche: $('#id_uniterecherche').val(),
                // codefil: 100,
                disponibilite: $('#id_disponibilite').val(),
                formationinitiale: $('#id_formationinitiale').val(),
                naturelicence: $('#id_naturelicence').val(),
                optionlicence: $('#id_optionlicence').val(),
                anneelicence: $('#id_anneelicence').val(),
                naturemasterun: $('#id_naturemasterun').val(),
                specialitemasterun: $('#id_specialitemasterun').val(),
                etablissementmasterun: $('#id_etablissementmasterun').val(),
                departementmasterun: $('#id_departementmasterun').val(),
                anneemasterun: $('#id_anneemasterun').val(),
                sourcefinancement: $('#id_sourcefinancement').val(),
                motivationthese: $('#id_motivationthese').val(),
                resumethese: $('#id_resumethese').val(),

                cycle: $('#id_cycle').val(),
                encadreur1: $('#id_encadreur1').val(),
                encadreur2: $('#id_encadreur2').val(),
                

                csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
            },
            beforeSend: function() {
                $('#ftco-loader').addClass('show');
            },
            success: function (data) {
                // $('#ftco-loader').removeClass('show');
                // alert("ok") 
                window.location.href = "/ecoledoctorale/sport/" // Le rediriger vers le step 5
                //Penser a sauver les donnees dans la session                                                                                                            
            },
            error: function (data) {
                // $('#ftco-loader').removeClass('show');
                // alert("Erreur AJAX");                                                                                                                          
            }
        })

    });

</script>
{% endblock content %}