ecoledoctorale/urls.py
from django.urls import path
from ecoledoctorale.views import *

app_name = 'ecoledoctorale'

urlpatterns = [
    path('civilite/<int:ecole>/', civilite, name='civilite'),
    path('civilite/', civilite, name='civilite'), 
    path('filiation/', filiation, name='filiation'), 
    path('ecole/', ecole, name='ecole'),
    path('sport/', sport, name='sport'),
    path('autre/', autres, name='autre'),
    path('searchdom_univ/', search, name='search'),
    path('fiche/<int:code>/', fiche, name='fiche'),
    path('fiche_view/<int:code>', ViewPDF.as_view(), name="pdf_view"),
    path('fiche_download/<int:code>/', DownloadPDF.as_view(), name="pdf_download"),
    path('get_fields/', get_fields_from_school, name='get_fields'),
    path('get_supstudy/', get_supstudy, name='get_supstudy_link'),
    path('get_departments/', get_departements_from_region, name='get_departments'),
    path('step_1/', validation_step_civilite, name='civilite_step_1'),
    path('step_2/', validation_step_filiation, name='filiation_step_2'),
    #path('step_3/', validation_step_etude, name='etude_step_3'),
    path('step_4/', validation_step_ecole, name='diplome_step_4'),
    path('step_5/', validation_step_sport, name='sport_step_5'),
    path('step_6/', validation_step_autre, name='autre_step_6'),
    path('get_step_data/<int:step>/<int:code>', get_step_data, name='get_step_data'),
]

falshfsfse/urls.py
from django.urls import path
from falshfsfse.views import *

app_name = 'falshfsfse'

urlpatterns = [
    path('civilite/<int:fac>/', civilite, name='civilite'),
    path('civilite/', civilite, name='civilite'),
    path('filiation/', filiation, name='filiation'),
    path('faculte/', faculte, name='faculte'),
    path('diplome/', diplome, name='diplome'),
    path('sport/', sport, name='sport'),
    path('autre/', autres, name='autre'),
    path('searchdom_univ/', search, name='search'),
    path('fiche/<int:code>/', fiche, name='fiche'),
    path('fiche_view/<int:code>/', ViewPDF.as_view(), name='pdf_view'),
    path('fiche_download/<int:code>/', DownloadPDF.as_view(), name='pdf_download'),
    path('get_fields/', get_fields_from_school, name='get_fields'),
    path('get_supstudy/', get_supstudy, name='get_supstudy_link'),
    path('get_departments/', get_departements_from_region, name='get_departments'),
    path('step_1/', validation_step_civilite, name='civilite_step_1'),
    path('step_2/', validation_step_filiation, name='filiation_step_2'),
    path('step_3/', validation_step_etude, name='etude_step_3'),
    path('step_4/', validation_step_diplome, name='diplome_step_4'),
    path('step_5/', validation_step_sport, name='sport_step_5'),
    path('step_6/', validation_step_autre, name='autre_step_6'),
    path('get_step_data/<int:step>/<int:code>', get_step_data, name='get_step_data'),
]

logement/urls.py
from django.urls import path
from logement.views import *

app_name = 'logement'

urlpatterns = [
    path('logement_civilite/', logement_civilite, name='logement_civilite'),
    path('logement_filiation/', logement_filiation, name='logement_filiation'),
    path('logement_faculte/', logement_faculte, name='logement_faculte'),
    path('logement_sport/', logement_sport, name='logement_sport'),
    path('logement_search/', logement_search, name='logement_search'),
    
    path('logement_fiche/<int:code>/', logement_fiche, name='logement_fiche'),
    path('logement_fiche_download/<int:code>/', Logement_DownloadPDF.as_view(), name="logement_pdf_download"),
    path('logement_fiche_view/<int:code>/', Logement_ViewPDF.as_view(), name="logement_pdf_view"),

    path('step_1/', validation_step_civilite, name='civilite_step_1'),
    path('step_2/', validation_step_filiation, name='filiation_step_2'),
    path('step_3/', validation_step_etude, name='etude_step_3'),
    path('step_4/', validation_step_sport, name='sport_step_4'),
    path('get_step_data/<int:step>/<int:code>', get_step_data, name='get_step_data'),
]

preinscription/urls.py
from django.contrib import admin
from django.urls import include, path
from falshfsfse import views
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.accueil, name='accueil'),
    path('formulaire/', include('falshfsfse.urls')),
    path('logement/', include('logement.urls')),
    path('ecoledoctorale/', include('ecoledoctorale.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    url(r'^rosetta/', include('rosetta.urls'))
]

falshfsfse/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remov` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.

from django.db import models
import uuid
import random


class Bilingue(models.Model):
    code_pre = models.CharField(max_length=50, unique=True)
    nom_etudiant = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        db_table = 'bilingue'


# Table not used
class CentreExams(models.Model):
    libelle = models.CharField(max_length=100, blank=True, null=True)
    nbre_candidat = models.IntegerField(blank=True, null=True)
    nbre_candidat_fac = models.IntegerField(blank=True, null=True)
    code = models.CharField(max_length=2, blank=True, null=True)
    nbre_cand_m1 = models.IntegerField(blank=True, null=True)
    nbre_cand_l2 = models.IntegerField(blank=True, null=True)
    nbre_cand_l3 = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    nbre_cand_specia = models.IntegerField(blank=True, null=True)
    nbre_cand_internat = models.IntegerField(blank=True, null=True)

    class Meta:
        db_table = 'centre_exams'


AGENCES_PAIEMENTS = (
    ('EXPRESS UNION', 'EXPRESS UNION'),
    ('UBA', 'UBA')
)

NIVEAUX = (
    ('L1', 'L1'),
    ('L2', 'L2'),
    ('L3', 'L3'),
    ('M1', 'M1'),
    ('M2', 'M2'),
    ('D1', 'D1'),
    ('D2', 'D2'),
    ('D3', 'D3')
)

STATUTS_MATRIMONIAUX = (
    ('MARIE(E)', 'MARIE(S)'),
    ('CELIBATAIRE', 'CELIBATAIRE'),
    ('DIVORCE(E)', 'DIVORCE(E)')
)

SITUATIONS_PROFESSIONNELLES = (
    ('SANS EMPLOI', 'SANS EMPLOI'),
    ('SALARIE(E)', 'SALARIE(E)'),
    ('EN AUTO-EMPLOI', 'EN AUTO-EMPLOI')
)

REGIMES_ENCADREMENTS = (
    ('DIRECTION', 'DIRECTION'),
    ('CO-DIRECTION', 'CO-DIRECTION'),
    ('CO-TUTELLE', 'CO-TUTELLE')
)
LANGUES = (
    ('FRANCAIS', 'FRANCAIS'),
    ('ANGLAIS', 'ANGLAIS')
)

SEXES = (
    ('MASCULIN', 'MASCULIN'),
    ('FEMININ', 'FEMININ')
)

# Fritz: je commente cette table car elle ne sert plus à rien
""" class DossiersCopy16092019(models.Model):
    inst1_id = models.IntegerField(blank=True, null=True)
    inst2_id = models.IntegerField(blank=True, null=True)
    inst3_id = models.IntegerField(blank=True, null=True)
    fil1_id = models.IntegerField()
    fil2_id = models.IntegerField(blank=True, null=True)
    fil3_id = models.IntegerField(blank=True, null=True)
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    date_nais = models.DateField()
    lieu_nais = models.CharField(max_length=50)
    sexe = models.CharField(max_length=1)
    langue = models.CharField(max_length=1)
    nato_id = models.IntegerField()
    tel = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    region_origine_id = models.IntegerField()
    region_examen_id = models.IntegerField()
    type_diplome_id = models.IntegerField(blank=True, null=True)
    serie = models.CharField(max_length=1, blank=True, null=True)
    moyenne = models.FloatField(blank=True, null=True)
    annee_obtention = models.IntegerField(blank=True, null=True)
    num_matricule = models.CharField(max_length=20, blank=True, null=True)
    code_centre = models.CharField(max_length=5, blank=True, null=True)
    code_jury = models.CharField(max_length=5, blank=True, null=True)
    mention_id = models.IntegerField(blank=True, null=True)
    grade_bio = models.CharField(max_length=1, blank=True, null=True)
    grade_bio_an = models.IntegerField(blank=True, null=True)
    grade_chim = models.CharField(max_length=1, blank=True, null=True)
    grade_chim_an = models.IntegerField(blank=True, null=True)
    mati_olevel = models.CharField(max_length=1, blank=True, null=True)
    grade_mati_olevel = models.CharField(max_length=1, blank=True, null=True)
    grade_mati_olevel_an = models.IntegerField(blank=True, null=True)
    decl_honneur = models.IntegerField()
    banque = models.CharField(max_length=40, blank=True, null=True)
    num_quittance = models.CharField(max_length=20, blank=True, null=True)
    num_ordre = models.CharField(unique=True, max_length=10, blank=True, null=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    stat_matri = models.CharField(max_length=100, blank=True, null=True)
    nom_pere = models.CharField(max_length=100, blank=True, null=True)
    profession_pere = models.CharField(max_length=100, blank=True, null=True)
    nom_mere = models.CharField(max_length=100, blank=True, null=True)
    profession_mere = models.CharField(max_length=100, blank=True, null=True)
    dept_origine_id = models.IntegerField(blank=True, null=True)
    adresse_parent = models.CharField(max_length=100, blank=True, null=True)
    annee_scol1 = models.CharField(max_length=9, blank=True, null=True)
    annee_scol2 = models.CharField(max_length=9, blank=True, null=True)
    annee_scol3 = models.CharField(max_length=9, blank=True, null=True)
    annee_scol4 = models.CharField(max_length=9, blank=True, null=True)
    annee_scol5 = models.CharField(max_length=9, blank=True, null=True)
    annee_scol_etab1 = models.CharField(max_length=100, blank=True, null=True)
    annee_scol_etab2 = models.CharField(max_length=100, blank=True, null=True)
    annee_scol_etab3 = models.CharField(max_length=100, blank=True, null=True)
    annee_scol_etab4 = models.CharField(max_length=100, blank=True, null=True)
    annee_scol_etab5 = models.CharField(max_length=100, blank=True, null=True)
    annee_scol_niv1 = models.CharField(max_length=50, blank=True, null=True)
    annee_scol_niv2 = models.CharField(max_length=50, blank=True, null=True)
    annee_scol_niv3 = models.CharField(max_length=50, blank=True, null=True)
    annee_scol_niv4 = models.CharField(max_length=50, blank=True, null=True)
    annee_scol_niv5 = models.CharField(max_length=50, blank=True, null=True)
    annee_scol_ser1 = models.CharField(max_length=5, blank=True, null=True)
    annee_scol_ser2 = models.CharField(max_length=5, blank=True, null=True)
    annee_scol_ser3 = models.CharField(max_length=5, blank=True, null=True)
    annee_scol_ser4 = models.CharField(max_length=5, blank=True, null=True)
    annee_scol_ser5 = models.CharField(max_length=5, blank=True, null=True)
    annee_scol_dipl1 = models.CharField(max_length=100, blank=True, null=True)
    annee_scol_dipl2 = models.CharField(max_length=100, blank=True, null=True)
    annee_scol_dipl3 = models.CharField(max_length=100, blank=True, null=True)
    annee_scol_dipl4 = models.CharField(max_length=100, blank=True, null=True)
    annee_scol_dipl5 = models.CharField(max_length=100, blank=True, null=True)
    annee_scol_san1 = models.CharField(max_length=50, blank=True, null=True)
    annee_scol_san2 = models.CharField(max_length=50, blank=True, null=True)
    annee_scol_san3 = models.CharField(max_length=50, blank=True, null=True)
    annee_scol_san4 = models.CharField(max_length=50, blank=True, null=True)
    annee_scol_san5 = models.CharField(max_length=50, blank=True, null=True)
    q1 = models.CharField(max_length=100, blank=True, null=True)
    q2 = models.CharField(max_length=100, blank=True, null=True)
    q31 = models.IntegerField(blank=True, null=True)
    q32 = models.CharField(max_length=100, blank=True, null=True)
    q41 = models.IntegerField(blank=True, null=True)
    q42 = models.CharField(max_length=100, blank=True, null=True)
    q52 = models.CharField(max_length=100, blank=True, null=True)
    q61 = models.IntegerField(blank=True, null=True)
    q62 = models.CharField(max_length=100, blank=True, null=True)
    q81 = models.IntegerField(blank=True, null=True)
    q82 = models.CharField(max_length=100, blank=True, null=True)
    q91 = models.CharField(max_length=100, blank=True, null=True)
    q92 = models.CharField(max_length=100, blank=True, null=True)
    q93 = models.CharField(max_length=100, blank=True, null=True)
    q10 = models.CharField(max_length=100, blank=True, null=True)
    q111 = models.CharField(max_length=100, blank=True, null=True)
    q112 = models.CharField(max_length=100, blank=True, null=True)
    q113 = models.CharField(max_length=100, blank=True, null=True)
    q12 = models.CharField(max_length=100, blank=True, null=True)
    q131 = models.IntegerField(blank=True, null=True)
    q132 = models.CharField(max_length=100, blank=True, null=True)
    q14 = models.CharField(max_length=100, blank=True, null=True)
    q51 = models.CharField(max_length=100, blank=True, null=True)
    q9 = models.IntegerField(blank=True, null=True)
    lieu_depot_id = models.IntegerField(blank=True, null=True)
    nom_banque = models.CharField(max_length=100, blank=True, null=True)
    date_paiement = models.DateField(blank=True, null=True)
    deposited = models.IntegerField(blank=True, null=True)
    institution_depot_id = models.IntegerField(blank=True, null=True)
    filiere_depot_id = models.IntegerField(blank=True, null=True)
    user_depot_id = models.IntegerField(blank=True, null=True)
    date_depot = models.DateTimeField(blank=True, null=True)
    dipl_etabl = models.CharField(max_length=100, blank=True, null=True)
    dipl_info_jury = models.CharField(max_length=100, blank=True, null=True)
    dipl_date_deli = models.DateField(blank=True, null=True)
    niv_acad = models.IntegerField(blank=True, null=True)
    examen_id = models.IntegerField(blank=True, null=True)
    accept_prive_etabl_id = models.IntegerField(blank=True, null=True)
    accept_prive = models.IntegerField(blank=True, null=True)
    type_etabl_c = models.CharField(max_length=1, blank=True, null=True)

falshfsfse/templates/falshfsfse/boutonsuivant.html
<div class="row m-auto center">
    <div class="col-sm-12 m-auto">
        {%if text == "Modifier"  %}
            <button type="submit" class="btn  btn-around2" style="min-width: 150px; max-width: 100%;">
                <i class="fas fa-edit"></i> Modifier
            </button>
        {% else %}
            <button type="submit" class="btn  btn-around2" style="min-width: 150px; max-width: 100%;">
                <i class="fas fa-plus"></i> Suivant
            </button>
        {% endif %}
    </div>
</div>

falshfsfse/templates/falshfsfse/civilite.html
{% extends 'falshfsfse/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
    {% with titre="civilité"%}
        {% include 'falshfsfse/menuetape.html' %}
    {% endwith %}
<div class="col-md-6">
    <h3>{% trans 'Préinscription en' %} {{ request.session.fac }}</h3>
    <h6>{% trans 'Tous les champs marqués d\'un' %} <span style="color:red; margin-top:3px;">*</span> {% trans 'sont obligatoires.' %}</h6>
    <form id='civilite_form' class='f1' name='civilite_form'>
        {% csrf_token %}
        
        {{ civilite_form| crispy }}
        
        <!-- <input type="button" onclick="prev()" name = "bouton_autre_prev" value="Précédent" class="btn btn-charte btn-lg" style="width: 116px"> -->
        <input type="submit" value="Suivant" class="btn btn-charte btn-lg" style="width: 116px">   
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> 
<script type="text/javascript">


    // function prev() {
    //     location.replace("/formulaire/autre/{{ request.session.code_fac }}")
    // }
    $( document ).ready(function() {


        function masquerShow(){
            // Masquer certains champs si statut professionel == Sans emploi
            if ($('#id_statutprofessionnel').val() == "SANS EMPLOI" || $('#id_statutprofessionnel').val() == "EN AUTO-EMPLOI" || $('#id_statutprofessionnel').val() == null) {
                $('#div_id_profession').hide()
                $('#div_id_lieudujob').hide()
                $('#div_id_grade').hide()
                $('#div_id_echelon').hide()
            }

            $("#id_statutprofessionnel").change(function () {

                if ($(this).val() == "SALARIE(E)") {
                    $('#div_id_profession').show()
                    $('#div_id_lieudujob').show()
                    $('#div_id_grade').show()
                    $('#div_id_echelon').show()
                }
                else{
                    $('#div_id_profession').hide()
                    $('#div_id_lieudujob').hide()
                    $('#div_id_grade').hide()
                    $('#div_id_echelon').hide()
                }

            });
        }


        function loadfield(callback){
            if(sessionStorage.getItem("codeUnique") != null && sessionStorage.getItem("codeUnique") != "" && sessionStorage.getItem("codeUnique") != undefined){
                // Recharger les valeurs soumises dans les champs
                $.ajax({
                    //type: 'POST',
                    url: '/formulaire/get_step_data/1/'+sessionStorage.getItem("codeUnique"),
                    data: {
                        //csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
                    },
                    dataType: 'json',
                    beforeSend: function() {
                        //$('#ftco-loader').addClass('show');
                    },
                    success: function (data) {
                        if (data['prenom'] != undefined && data['prenom'] != ""){
                            document.diplome_form.prenom.value = data['prenom']  
                        }
                        // document.civilite_form.prenom.value = data['prenom'] == undefined ? "" : data['prenom']
                        if (data['nom'] != undefined && data['nom'] != ""){
                            document.diplome_form.nom.value = data['nom']  
                        }
                        // document.civilite_form.nom.value = data['nom'] == undefined ? "" : data['nom']
                        if (data['sexe'] != undefined && data['sexe'] != ""){
                            document.diplome_form.sexe.value = data['sexe']  
                        }
                        // document.civilite_form.sexe.value = data['sexe'] == undefined ? "" : data['sexe']
                        if (data['datenaissance'] != undefined && data['datenaissance'] != ""){
                            document.diplome_form.datenaissance.value = data['datenaissance']  
                        }
                        // document.civilite_form.datenaissance.value = data['datenaissance'] == undefined ? "" : data['datenaissance']
                        if (data['dateprecise'] != undefined && data['dateprecise'] != ""){
                            document.diplome_form.dateprecise.value = data['dateprecise']  
                        }
                        // document.civilite_form.dateprecise.value = data['dateprecise'] == undefined ? "" : data['dateprecise']
                        if (data['lieunaissance'] != undefined && data['lieunaissance'] != ""){
                            document.diplome_form.lieunaissance.value = data['lieunaissance']  
                        }
                        // document.civilite_form.lieunaissance.value = data['lieunaissance'] == undefined ? "" : data['lieunaissance']
                        if (data['numerocni'] != undefined && data['numerocni'] != ""){
                            document.diplome_form.numerocni.value = data['numerocni']  
                        }
                        // document.civilite_form.numerocni.value = data['numerocni'] == undefined ? "" : data['numerocni']
                        if (data['adresse'] != undefined && data['adresse'] != ""){
                            document.diplome_form.adresse.value = data['adresse']  
                        }
                        // document.civilite_form.adresse.value = data['adresse'] == undefined ? "" : data['adresse']
                        if (data['telephone'] != undefined && data['telephone'] != ""){
                            document.diplome_form.telephone.value = data['telephone']  
                        }
                        // document.civilite_form.telephone.value = data['telephone'] == undefined ? "" : data['telephone']
                        
                        document.civilite_form.email.value = data['email'] == undefined ? "" : data['email']
                        document.civilite_form.statutmarital.value = data['statutmarital'] == undefined ? "" : data['statutmarital']
                        document.civilite_form.premierelangue.value = data['premierelangue'] == undefined ? "" : data['premierelangue']
                        document.civilite_form.statutprofessionnel.value = data['statutprofessionnel'] == undefined ? "" : data['statutprofessionnel']
                        if (data['statutprofessionnel'] == "SALARIE(E)") {
                            $('#div_id_profession').show()
                            $('#div_id_lieudujob').show()
                            $('#div_id_grade').show()
                            $('#div_id_echelon').show()
                        }
                        document.civilite_form.profession.value = data['profession'] == undefined ? "" : data['profession']
                        document.civilite_form.lieudujob.value = data['lieudujob'] == undefined ? "" : data['lieudujob']
                        document.civilite_form.grade.value = data['grade'] == undefined ? "" : data['grade']
                        document.civilite_form.echelon.value = data['echelon'] == undefined ? "" : data['echelon']

                    },
                    error: function (data) {
                        //$('#ftco-loader').removeClass('show');
                        //alert("Erreur AJAX");                                                                                                                          
                    }
                })
            }
        }

        $.when( loadfield() ).done(function() {
            setTimeout(function(){

                masquerShow();
            },100);
            
        });
    });


    $( document ).on('submit', '#civilite_form', function(e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '/formulaire/step_1/',
            data: {
                prenom: $('#id_prenom').val(),
                nom: $('#id_nom').val(),
                datenaissance: $('#id_datenaissance').val(),
                dateprecise: document.civilite_form.dateprecise.value,
                lieunaissance: $('#id_lieunaissance').val(),
                numerocni: $('#id_numerocni').val(),
                sexe: $('#id_sexe').val(),
                adresse: $('#id_adresse').val(),
                telephone: $('#id_telephone').val(),
                email: $('#id_email').val(),
                statutmarital: $('#id_statutmarital').val(),
                premierelangue: $('#id_premierelangue').val(),
                statutprofessionnel: $('#id_statutprofessionnel').val(),
                profession: $('#id_profession').val(),
                lieudujob: $('#id_lieudujob').val(),
                grade: $('#id_grade').val(),
                echelon: $('#id_echelon').val(),

                csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val()
            },
            beforeSend: function() {
                $('#ftco-loader').addClass('show');
            },
            success: function (data) {
                //$('#ftco-loader').removeClass('show');
                sessionStorage.codeUnique = data['code']
                window.location.href = "/formulaire/autre/" // Le rediriger vers le step 2
                // Penser a sauver les donnees dans la session
                // Penser à vérifier que tous les champs sont remplis avant d'envoyer les données
            },
            error: function (data) {
                $('#ftco-loader').removeClass('show');
                //alert("Erreur AJAX");                                                                                                                          
            }
        })

    });

</script>
{% endblock content %}

falshfsfse/templates/falshfsfse/menuetape.html
{% load i18n %}
<style>
    .link-img{
        color: inherit;
    }
    .link-img:hover{
        color: inherit;
    }
</style>

<div class="col-md-3 zozo f1-steps" style="/*margin-right: -165px;*/">
    {% if request.session.code_fac %}
        <div class="f1-step {% ifequal titre 'civilité' %}active{% endifequal %}">
            <div class="f1-step-icon"><a class="link-img" href="{% url 'falshfsfse:civilite' request.session.code_fac %}"><i class="fa fa-id-card"></i></a></div>
            <p><a href="{% url 'falshfsfse:civilite' request.session.code_fac%}">{% trans 'Etat civil' %}</a></p>
        </div>
    {% else %}
        <div class="f1-step {% ifequal titre 'civilité' %}active{% endifequal %}">
            <div class="f1-step-icon"><a class="link-img" href="{% url 'falshfsfse:civilite' 1 %}"><i class="fa fa-id-card"></i></a></div>
            <p><a href="{% url 'falshfsfse:civilite' 1 %}">{% trans 'Etat civil' %}</a></p>
        </div>
    {% endif %}
    <div class="f1-step {% ifequal titre 'autre' %}active{% endifequal %}">
        <div class="f1-step-icon"><a class="link-img" href="{% url 'falshfsfse:autre' %}"><i class="fa fa-info"></i></a></div>
        <p><a href="{% url 'falshfsfse:autre' %}">{% trans 'Informations de paiement' %}</a></p>
    </div>
    <div class="f1-step {% ifequal titre 'filiation' %}active{% endifequal %}">
        <div class="f1-step-icon"><a class="link-img" href="{% url 'falshfsfse:filiation' %}"><i class="fa fa-user"></i></a></div>
        <p><a href="{% url 'falshfsfse:filiation' %}">{% trans 'Informations de filiation' %}</a></p>
    </div>
    <div class="f1-step {% ifequal titre 'faculté' %}active{% endifequal %}">
        <div class="f1-step-icon"><a class="link-img" href="{% url 'falshfsfse:faculte' %}"><i class="fa fa-university"></i></a></div>
        <p><a href="{% url 'falshfsfse:faculte' %}">{% trans 'Faculté et études souhaitées' %}</a></p>
    </div>
    <div class="f1-step {% ifequal titre 'diplome' %}active{% endifequal %}">
        <div class="f1-step-icon"><a class="link-img" href="{% url 'falshfsfse:diplome' %}"><i class="fa fa-graduation-cap"></i></a></div>
        <p><a href="{% url 'falshfsfse:diplome' %}">{% trans 'Diplômes présentés' %}</a></p>
    </div>
    <div class="f1-step {% ifequal titre 'sport' %}active{% endifequal %}">
        <div class="f1-step-icon"><a class="link-img" href="{% url 'falshfsfse:sport' %}"><i class="fa fa-futbol-o"></i></a></div>
        <p><a href="{% url 'falshfsfse:sport' %}">{% trans 'Informations sportives' %}</a></p>
    </div>
</div>

falshfsfse/templates/falshfsfse/search.html
{% extends 'falshfsfse/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}
    <title>UY1 - Suivre ma demande de préinscription</title>
{% endblock title %}

{% block content %}
<div class="col-md-6">
    <h2 style="color:#337ab7; font-weight:650">UNIVERSITE DE YAOUNDE I</h2>
    <p style="font-size:20px">OPERATION DE PREINSCRIPTION <span id="ann"></span>
    <form id='search_form'  name='search_form' class='f1'>
        {% csrf_token %}
        
        {{ search_form| crispy }}
        
        <input type="submit" value="Afficher votre fiche" class="btn btn-charte btn-lg" style="">   
    </form>
    <div style="height:120px;"></div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> 
<script>

	$( document ).ready(function() {
		annee = new Date().getFullYear()
		anneeSuiv = new Date().getFullYear() + 1
		$('#ann').html( annee + "-" + anneeSuiv)
	});

    $( document ).on('submit', '#search_form', function(e) {
        e.preventDefault();
        code = $('#id_code').val();
        if (code != "" && $.isNumeric( code)) {
            var str = code.toString()
            if (str.startsWith("2")) {
                window.location.href = "/formulaire/fiche/"+ str +"/"
            }

            else if (str.startsWith("3")) {
                window.location.href = "/ecoledoctorale/fiche/"+ str +"/"
            }

            else if (str.startsWith("1")) {
                window.location.href = "/logement/logement_fiche/"+ str +"/"
            }
            else{
                alert("Mauvais format de code! Veuillez renseigner le bon code")
            }
            
        }
        else{
            alert("Veuillez renseigner le bon code")
        }

    });
	
</script>
{% endblock content %}

{% block aide %}

{% endblock %}